apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: host-id
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: host-id
    spec:
      containers:
      - name: frontend
        image: iftachsc/host-id:1.0
        ports:
        - containerPort: 3000